# Checkov Configuration
# https://www.checkov.io/2.Basics/CLI%20Command%20Reference.html

# Skip specific checks with justification
skip-check:
  # CKV_AWS_18: S3 bucket should have access logging configured
  # Justification: State bucket doesn't need access logging for cost reasons
  - CKV_AWS_18
  
  # CKV_AWS_21: S3 bucket should have versioning enabled
  # Justification: Already enabled via separate resource
  - CKV_AWS_21

# Frameworks to scan
framework:
  - terraform

# Output formats (Phase 2: Added SARIF for GitHub Security tab)
output:
  - cli
  - json
  - sarif

# Compact output for CI
compact: true

# Soft fail mode (don't fail pipeline on findings)
# Set to false when transitioning from MVP to production
soft-fail: true
