# tfsec configuration
# https://aquasecurity.github.io/tfsec/latest/guides/configuration/config/

# ---------------------------------------------------------
# Minimum severity to report
# Valid values: LOW, MEDIUM, HIGH, CRITICAL
# ---------------------------------------------------------
minimum_severity: HIGH

# ---------------------------------------------------------
# Exclude specific checks with justification
# (Keep exclusions small; only use when truly needed)
# ---------------------------------------------------------
exclude:
  # S3 bucket access logging (not required for cost reasons)
  - AWS018
  - aws-s3-enable-bucket-logging

  # S3 versioning managed outside Terraform
  - aws-s3-enable-versioning

  # IAM password policy — using SSO instead of IAM users
  - aws-iam-set-minimum-password-length

# ---------------------------------------------------------
# Exclude directories
# ---------------------------------------------------------
exclude_paths:
  - .terraform/**
  - "**/.terraform/**"

# ---------------------------------------------------------
# Output formats (for CLI or other tooling)
# NOTE: GitLab CI will override format for JUnit, but keeping defaults is fine
# ---------------------------------------------------------
format:
  - default
  - json
  - sarif

# ---------------------------------------------------------
# Custom checks directory (optional)
# Uncomment if you create custom rules under `.tfsec/`
# ---------------------------------------------------------
# custom-check-dir: .tfsec

# ---------------------------------------------------------
# Severity overrides (optional)
# Example:
# severit
